name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write  # ✅ Moved permissions to the correct place

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}  # ✅ Use a PAT instead of GITHUB_TOKEN

      - name: Build and Push Docker Image
        run: |
          docker buildx build --push \
            --tag ghcr.io/ravin000dra/demo-gitops:${{ github.sha }} .

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Set up Kubernetes Kubeconfig
        run: |
          mkdir -p $HOME/.kube  # ✅ Ensure the directory exists
          echo "${{ secrets.KUBE_CONFIG_DEV }}" > $HOME/.kube/config  # ✅ Write config file
          chmod 600 $HOME/.kube/config  # ✅ Secure the file

      - name: Deploy to Dev environment
        run: |
          kubectl apply -f k8s/deployment-dev.yaml

  deploy-test:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Set up Kubernetes Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG_TEST }}" > $HOME/.kube/config

      - name: Deploy to Test environment
        run: |
          kubectl apply -f k8s/deployment-test.yaml

  deploy-prod:
    needs: deploy-test
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Set up Kubernetes Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG_PROD }}" > $HOME/.kube/config

      - name: Deploy to Prod environment
        run: |
          kubectl apply -f k8s/deployment-prod.yaml
