name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}         # Use the GitHub user name
          password: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/username/my-app:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/username/my-app:${{ github.sha }}

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Set up Kubernetes Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG_DEV }}" > $HOME/.kube/config

      - name: Deploy to Dev environment
        run: |
          kubectl apply -f k8s/deployment-dev.yaml

  deploy-test:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - name: Set up Kubernetes Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG_TEST }}" > $HOME/.kube/config

      - name: Deploy to Test environment
        run: |
          kubectl apply -f k8s/deployment-test.yaml

  deploy-prod:
    needs: deploy-test
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Set up Kubernetes Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG_PROD }}" > $HOME/.kube/config

      - name: Deploy to Prod environment
        run: |
          kubectl apply -f k8s/deployment-prod.yaml
